aws:
  sns:
    registered-time-tracking:
      name: prd-time-tracking-event-topic

spring:
  cloud:
    aws:
      region:
        static: us-east-1
  data:
    mongodb:
      database: paymentdb
      port: 27017

payment-service:
  configuration:
    s3:
      mongo-ssl:
        bucket: # defined-at-task-definition
        file: global-bundle.pem