version: "3.9"

services:
  localstack:
    container_name: localstack
    image: fiapsoat2grupo13/hackathon-localstack-resources:latest
    platform: linux/amd64
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=${DEBUG:-0}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - time-tracking-network

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - "27017:27017"
    networks:
      - time-tracking-network

networks:
  time-tracking-network:
    driver: bridge
